### ISSUE TITLE
🚸 'Open a diagram' Button is not intuitively chosen

### ISSUE THREAD

**Issue by dominikkaminski** [process-engine/bpmn-studio#1356]
#### Describe your issue

When looking at Solutions Explorer, the buttons are unintuitively chosen:

1. File -> Implies that a new Solution will be created.
2. Folder -> Implies that a already existing Solution will be opened.
3. Plug -> Implies nothing correlated to a solution to me.

#### How can others reproduce the issue?

Open BPMN Studio.

#### Possible solution

I would suggest following Font Awesome Icons

0. Folder-plus -> Create a new Folder / Solution on disk
2. Folder-open -> Opens an already existing Folder / Solution
1. File-import -> Imports an existing diagram
3. Cloud -> Opens a remote Solution 

#### What's your setup

- BPMN-Studio Version (`4.21.0`):

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by Vyperus** [comment]
Thanks for your recommendations!

We will discuss this in our team.
I will notify you if something regarding this Issue happens.

**Comment by Vyperus** [comment]
Well that took for ever. I'm sorry that I couldn't come to this faster. We just discussed your recommendations in the team and came up the following changes to the icons.

"Open File Icon"
Currently: file
New: file-edit

"Open Folder Icon"
Does exactly what it implies and will stay the same.

"Open Remote Solution Icon"
Will stay the same since a plug shows the process of connecting to a "server/remote solution" better than a cloud.

I will open a PR for this changes soon.
Stay tuned!

**Comment by ElRaptorus** [comment]
@Vyperus 
I just noticed that the `file-edit` button is only included with fontawesome-pro. 
Meaning, we cannot use that icon.

This is a list of the free file icons we could use:
https://fontawesome.com/icons?d=gallery&c=files&m=free

I don't think any of these icons are a better match than the one we currently have in place.
/cc @dominikkaminski

**Comment by ElRaptorus** [comment]
@Vyperus 
So after trudging through the collection of available icons I came across this one:
https://fontawesome.com/icons/edit?style=solid

This is rather generic, but it should serve to illustrate the "edit" function, imho.

In BPMN Studio it would look like this:
![Bildschirmfoto 2019-03-18 um 14 52 25](https://user-images.githubusercontent.com/15343316/54534828-7e518980-498d-11e9-9ee5-0a9acd9f7c29.png)

Alternatively, there are a number of pen-icons that might fit:
https://fontawesome.com/icons?d=gallery&c=business&m=free

This one, for instance:
![Bildschirmfoto 2019-03-18 um 14 56 57](https://user-images.githubusercontent.com/15343316/54535116-1f404480-498e-11e9-8915-47ff42eb3cfb.png)

Since we are editing *business* processes here anyway, it may not be such a bad idea to switch to business-related icons anyway.

/cc @lsueslack Any recommendations?
