### ISSUE TITLE
🐛 Studio Breaks When Leaving Cronjobs Running for Too Long

### ISSUE THREAD

**Issue by SteffenKn** [process-engine/bpmn-studio#1574]
## Description

I get the following error when leaving cronjobs running for too long:

<img width="547" src="https://user-images.githubusercontent.com/20394992/60971231-f7e9fa80-a323-11e9-8d42-71d2a1133f86.png">

## Reproduction

- Deploy [this](https://github.com/process-engine/bpmn-studio/files/3377578/2.bpmn.zip) diagram
- Wait some time
- Restart the studio

**Comment by ElRaptorus** [comment]
I don't think this is an issue with the Studio. 

Judging by the path contained in this error, this most likely happens because the cronjob started too many process instances for the metrics repository to handle.

The thing about the logs and metrics is that all of them are grouped in files named after the process model for which they were recorded.

So if I start, say, 100 process instances for the same process model, we'd get more than a hundred file handlers for the same file. 

I guess during normal execution there is just enough time between each write operation to prevent collisions, but when all the ProcessInstances resume after a restart, it could be enough to cause this error.

**Comment by ElRaptorus** [comment]
So basically, this is in issue with how the ProcessEngine handles metrics and logs for large amounts of concurrently running ProcessInstances. 

We need a concept on how to improve this before we can actually fix this.

**Comment by ElRaptorus** [comment]
See https://github.com/process-engine/process_engine_runtime/issues/374

**Comment by ElRaptorus** [comment]
@alexanderkasten @SteffenKn @rrrene 
Ist das hier bei irgendjemandem nochmal wieder aufgeteten?
Ich hatte das jetzt eine Weile nicht mehr.

**Comment by SteffenKn** [comment]
Ich habe testweise mal die Stable für ein paar Stunden laufen lassen mit einem Cronjob der alle 2 Sekunden läuft.
Den Fehler an sich kann ich nicht mehr reproduzieren.
Mein Backend reagiert allerdings trotzdem nicht mehr.

**Comment by SteffenKn** [comment]
Da der Fehler seit einer Weile scheinbar nicht mehr auftritt schließe ich das Issue erstmal.
