### ISSUE TITLE
✨Automatically Complete Topics in Service Task

### ISSUE THREAD

**Issue by DevBastiS** [process-engine/bpmn-studio#1590]
## Description

To further support the user "programming" the processes to make them run in the PE it would be really nice if BPMN-Studio would know what ETWs are currently connected to the PE.

With this information it would be possible to display the available topics in External Task Section of the Property Panel and let the user choose one or even auto complete the input.

**Comment by ElRaptorus** [comment]
That's not so easy to do, since the workers aren't actually 'connected' to the ProcessEngine.
They only make repeated polls against it.
Just like the Studio does. 

I'm not too sure if the ProcessEngine should even know or care who is making requests against it. 

But I like the idea of an ETW overview. I agree that it would be quite a boon to have something like this. 
I will give this some thought.  

/cc @rrrene

**Comment by rrrene** [comment]
@Vyperus Das wäre mit Sicherheit superkomfortabel!

Die große Frage hier ist mMn, ob das nicht für sich genommen schon sehr sensible Daten sind (zu wissen, welche Topics es gibt, insbesondere, da wir inzwischen ja auch Topics haben können, die einen dynamischen Teil haben - bspw. "user:4325").

Wir sollten die Idee definitiv im Hinterkopf behalten und vorher ein Konzept schreiben, insbesondere, ob das wirklich die PE selber können muss, wie lange nach dem letzten Poll die Topics "gelten" und wie man das in Produktion deaktivieren kann! :+1: /cc @ElRaptorus

**Comment by ElRaptorus** [comment]
Wird für das BPMN Studio nicht mehr umgesetzt.
