### ISSUE TITLE
🐛 Update of BPMN-Studio hangs at 100% and reports error

### ISSUE THREAD

**Issue by cmg-dev** [process-engine/bpmn-studio#1994]
## Description

Updating the Studio from 5.11.0 to 5.13.0 hangs and reports error.

## Reproduction

1. Open Studio 5.11.0
2. See the "Updates available" message
3. Click the BPMN Studio icon
4. See that the download start:

   <img width="1792" alt="Screenshot 2020-03-20 at 11 28 18" src="https://user-images.githubusercontent.com/4034128/77155700-384a6c80-6a9e-11ea-9067-2743071e6d27.png">
   
   And continues normally: 

   <img width="1792" alt="Screenshot 2020-03-20 at 11 28 24" src="https://user-images.githubusercontent.com/4034128/77155704-3b455d00-6a9e-11ea-8742-52062809b3e1.png">

5. The download hangs at 100% 

   <img width="1792" alt="Screenshot 2020-03-20 at 11 28 30" src="https://user-images.githubusercontent.com/4034128/77155720-3f717a80-6a9e-11ea-8455-6a5eec559aeb.png">

6. Restarting the Studio brings up this message:

   <img width="428" alt="Screenshot 2020-03-20 at 11 31 24" src="https://user-images.githubusercontent.com/4034128/77155790-5fa13980-6a9e-11ea-9e27-2f9689fc20b5.png">

## My setup

> You can remove this section, if it's irrelevant to the issue

- OS (macOS Catalina):

**Comment by alexanderkasten** [comment]
Thanks for your bug report. In the versions v5.11.0 and v5.11.1 the AutoUpdater did not work because a bug in the electron module `net` was present. The bug was fixed with v5.11.2.

https://github.com/process-engine/bpmn-studio/releases/tag/v5.11.2

Unfortunately, you have to update v5.11.0 and v5.11.1 manually via the GitHub releases page.
