### ISSUE TITLE
Validate diagrams before saving

### ISSUE THREAD

**Issue by robpal94** [process-engine/bpmn-studio#507]
#### Describe your issue
Currently the validation of a diagram only happens, if you evaluate the `enableSaveButton` and `disableSaveButton` Events, thrown by the Event aggregator. 

Regardless of the diagrams state, you can simply throw a `saveDiagram` message over the EventAggregator and the diagram will be saved. There is no dedicated check, if the diagram is valid. This behavior may leads to an issue like #501. 

In my opinion it would be better to add an additional check, if the diagram is valid, to the `saveDiagram` Method to prevent saving of an invalid diagram. 

#### Possible solution
Validate the diagram in the `saveDiagram` method before you actually save the diagram.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by LeoTT** [comment]
Whoever looks at this, please reevaluate whether the following function is still required:
https://github.com/process-engine/bpmn-studio/blob/2179f23a30815d751737e222484b4bafb0e81211/src/modules/processdef-detail/processdef-detail.ts#L229 

It filters out empty formDatas inside of extensionsElements. But why? I could not reproduce any errors caused by empty formData and camunda modeler seems to support empty formDatas (tested it).

Either way I would not expect a validate function to produce side effects to the diagram.

**Comment by robpal94** [comment]
I would at least rename this method to something like `convertToCamundaXML` since _validate_ is very misleading in this context.

**Comment by cmg-dev** [comment]
I'm at this currently.
