### ISSUE TITLE
🐛 Process Always Contains Changes

### ISSUE THREAD

**Issue by Paulomart** [process-engine/bpmn-studio#542]
#### Describe your issue

If you open this [process](https://github.com/process-engine/bpmn-studio/files/2187720/process.zip) in BPMN Studio, it will always contain changes.

<img width="439" alt="grafik" src="https://user-images.githubusercontent.com/4148404/42620873-86c4c95a-85bc-11e8-8e8a-2ee58398dac1.png">

#### How can others reproduce the issue?

- Open via file repo or import the process 
- Open the process via solution explorer
- Go to another process via solution explorer
- Dialog shows, even with no changes made!

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by SteffenKn** [comment]
This is because the BPMN-Studio adds extensionElements to the Start Event when its undefined.

This always happens for processes that have never been saved in the BPMN studio before, regardless of whether they were imported from another BPMN Modeler or created by the BPMN-Studio.

The created extensionElement looks like this (new Value):

<img width="1065" src="https://user-images.githubusercontent.com/20394992/42675295-ab0cce0e-8673-11e8-8da4-4ab9b475b16b.png">

**Comment by robpal94** [comment]
The general problem is, that the _unsaved state_ will always be set, if the _diagramChange_ event is fired.

Also, the xml looks kinda different if you change something, revert your changes an regenerate the xml. This makes it hard to distinguish, if we really changed something.
