### ISSUE TITLE
Downloaded installer is marked as "not trustworthy" in chrome

### ISSUE THREAD

**Issue by robpal94** [process-engine/bpmn-studio#657]
#### Describe your issue
When downloading the bpmn-studio installer from the release page, chrome marks it as _not trustworthy_ and recommends the user to delete it. 

This may confuse windows users since they can think, that the bpmn-studio installer is some kind of malicious.

#### How can others reproduce the issue?
* Download the _bpmn-studio-setup-...exe_ from the [releases page](https://github.com/process-engine/bpmn-studio/releases) using chrome
* Look at the finished download

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by cmg-dev** [comment]
This is, for the best of our knowledge, for all GitHub downloads the case.

We will do it like this:

1. describe this in the documentation.

**Comment by heikomat** [comment]
This is not windows only, it also happens on macOS:

<img width="694" alt="bildschirmfoto 2018-12-01 um 00 32 08" src="https://user-images.githubusercontent.com/20770029/49320187-9dbcc780-f500-11e8-8d66-81247fc0e06b.png">

-> Removing the `Windows Only`-Label

**Comment by heikomat** [comment]
> This is, for the best of our knowledge, for all GitHub downloads the case.
> 
> We will do it like this:
> 
> 1. describe this in the documentation.

This is not because the files are hosted on github. downloading the zip, reuploading it somewhere else and downloading it from there raises the same warning.

It is known, that google sometimes blocks unknown downloads, if "Google Safe Borwsing" doesn't know/trust them (as described [here](https://support.google.com/webmasters/answer/3258249) (at the bottom)), but i don't think this is the problem, as the download isn't blocked immediately, but finishes downloading before being marked as uncommon.

I assume the problem (at least for the mac-zip-download) is, that it is a zip that contains binary files.
I did some testing, and downloading zips seems to be no problem, as long they don't contain any binary files.

When putting the smallest binary file i have (PowerLog, ~25KB) in a zip and downloading it, the download is flagged. Downloading that binary directly, without it being in a zip file does not flag the download

**Comment by rrrene** [comment]
Wir können das nicht reproduzieren. Bitte das Issue wieder öffnen, falls es noch ein Problem ist!
