### ISSUE TITLE
Uncaught Error when opening the detail view

### ISSUE THREAD

**Issue by robpal94** [process-engine/bpmn-studio#915]
#### Describe your issue

When opening a diagram detail view, the following StackTrace gets thrown: 
```
Uncaught TypeError: Cannot read property 'trim' of undefined
    at o (management_api_client_service.ts:99)
    at management_api_client_service.ts:99
o @ management_api_client_service.ts:99
(anonymous) @ management_api_client_service.ts:99
```

#### How can others reproduce the issue?

* Open a diagram (on the filesystem or the ProcessEngine)
* Look at the dev. console

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by LeoTT** [comment]
Not sure why and when, but sometimes this error leads me to the vendor-bundle, which allowed me to check where it came from.
```
Uncaught TypeError: Cannot read property 'trim' of undefined
    at o (scripts/vendor-bundle.js:180528)
```
The regarding line comes from the highlightjs package(which is being used in the xml view).
The error happens when you are not in the xml view. 

Somewhat related to #912 I think.

**Comment by Vyperus** [comment]
Thanks @LeoTT I will have a look into this!
