### ISSUE TITLE
🐛 The Waiting Room Sometimes Incorrectly Says "Process Stopped" Immediately After It Has Started 

### ISSUE THREAD

**Issue by SteffenKn** [process-engine/bpmn-studio#932]
#### Describe your issue

The waiting room sometimes incorrectly says "process stopped" immediately after it has started.

Related to https://github.com/process-engine/process_engine_runtime/issues/51

#### How can others reproduce the issue?

- Open up the BPMN-Studio
- Run a process with an user task (maybe you need to do this multiple times)
- Notice that the process may stop immediately

#### Possible solution

- Implement a retry count for the polling of the waiting room

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by Vyperus** [comment]
This shouldn't be happening anymore. Closing this for now.

**Comment by SteffenKn** [comment]
I think the only reason this won't happen anymore is because the Live Execution Tracker takes a little longer to request the active correlations.
We should definitely keep this in mind as this problem is not fixed in the backend yet: https://github.com/process-engine/process_engine_runtime/issues/176

**Comment by ElRaptorus** [comment]
@SteffenKn 
I think you wanted to reference this issue here: https://github.com/process-engine/process_engine_runtime/issues/54
This problem hasn't anything to do with BoundaryEvents. 

Btw., there really isn't much the backend can do about this (for the reasons explained in the linked issue), but you can easily work around this, by making use of the Notification-Feature. 😉
